apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nfs-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nfs
  template:
    metadata:
      labels:
        app: web-nfs
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-volume
          mountPath: /usr/share/nginx/html  # Path where Nginx serves files
        envFrom:
        - configMapRef:
            name: web-nfs-env  # Referencing the ConfigMap
      volumes:
      - name: nfs-volume
        nfs:
          server: $(NFS_SERVER)  # Using the environment variable from ConfigMap
          path: $(NFS_PATH)      # Using the environment variable from ConfigMap
