apiVersion: v1
kind: Service
metadata:
  name: web-nfs-service
spec:
  selector:
    app: web-nfs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Exposing on this NodePort
  type: NodePort
